
version: "3.7"


services:
  
  item-app:
    
    image: ghcr.io/arrow2601/item-app:v1
    
    
    depends_on:
      - item-db
    
    restart: always
    
    ports:
      - 80:8080

  
  item-db:
    
    image: mongo:3
    
    restart: always
    
    volumes:
      - app-db:/data/db


volumes:
  app-db:
